### ISSUE TITLE
Support Ruby 2.4, 2.5 and 2.6 on Windows

### ISSUE THREAD

**Issue by ukolovda** [mfazekas/bcrypt_pbkdf-ruby#1]
Please, add support Ruby 2.4, 2.5 and 2.6 on Windows.

**Comment by marcparadise** [comment]
This is also affecting us over at Chef as we work on upgrading our components for 2.7 compatibility. 

@mfazekas will you be able to push the updated gem if I submitted a PR to add 2.5-2.7 to the windows gem build?

**Comment by mfazekas** [comment]
@marcparadise  sure i'll try to, please submit a PR!

**Comment by marcparadise** [comment]
Thanks @mfazekas , I'll have that out shortly
